### ISSUE TITLE
Some IP addresses are not belonging to Cloudflare

### ISSUE THREAD

**Issue by ErfanM98** [SafaSafari/ss-cloud-scanner#20]
بعضی از آی پی ها نه تنها متعلق به کلاد فلر نیستن بلکه برای سرویس های داخلی هستن مثلا این رنج 185.143.232.0/22 برای ابرآروان هستش

**Comment by SafaSafari** [comment]
به نکته خیلی جالبی اشاره کردین
ظاهرا ابر آروان بعضی از سایت های روی کلادفلر رو تونل میکنه
مثلا دیسکورد رو با این دستور تست کنید

`curl 185.143.232.0 -H "Host: discord.com" -v`

همونطور که میبینید هدر های کلادفلر برمیگرده و ریدایرکت به https جواب میده
خیلی جالب شد =))))

**Comment by ErfanM98** [comment]
جالب جواب میده که باید ریدایرکت بشه کاربر به https در حالی که tls روی اون آی پی کار نمیکنه 
`curl https://discord.com/ --resolve 'discord.com:443:185.143.232.0' -v`
رو دامنه اصلی cloudflare.com هم دقیقا همین شکلی هستش. اما مثلا روی dash.cloudflare.com در کل کار نمیکنه. روی دامنه شخصی هم امتحان کردم در هر دو حالت جواب نداد.
احتمالا ابرآروان داشته نوعی transparent proxy رو تست میکرده.
من فکر میکنم این رنج باید حذف بشه از لیست

**Comment by SafaSafari** [comment]
اهوم
بزودی رنج های این دسته رو حذف میکنم👍
ممنون❤️
