### ISSUE TITLE
0,1,2,3 IPs

### ISSUE THREAD

**Issue by aliafshany** [SafaSafari/ss-cloud-scanner#6]
Thank you for this amazing app!
I was wondering why the results of each scan always end with an IP address of the form x.x.x.0 (1-2-3)? Does the script not scan any other IP numbers?

Best regards.

**Comment by SafaSafari** [comment]
yes you're right
because if it scans all ips in range, and uses 0.5 MB for every IP, a complete scan of a range takes 127 MB of bandwidth
it needs 367 GB for a complete scan :))

as a rule, if a IP returns in scan process, /24 subnets of its is good

**Comment by aliafshany** [comment]
@SafaSafari 

now i get it :))
cool, btw can we modify it in a way that can scan all IPs in a range? i mean not all of the ranges, only a few, but a thorough scan.
I mean, we can customize the IP txt file.

**Comment by SafaSafari** [comment]
Yes, it is possible, but it only confuses the user =))

**Comment by aliafshany** [comment]
hmm, you can try to add another prompt for that.
so the user can easily enter Y/N in order to scan thoroughly.

could you please try adding it?

**Comment by SafaSafari** [comment]
yes, of course :+1:

**Comment by aliafshany** [comment]
I am grateful for your time and effort invested in this.

**Comment by SafaSafari** [comment]
thanks :rose:
