### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by mfat** [SafaSafari/ss-cloud-scanner#7]
Please add a linux version too :) Thanks Safa jan!

**Comment by SafaSafari** [comment]
hi bro,
you can run this project on Linux easy as drinking water :)))
just install Python and pip with package manager (depends on Linux distro) and continue like Android installation guide :))

ریدمی رو فارسی زدیم، مشکلات رو انگلیسی حل میکنیم :joy: :joy: :joy:

**Comment by SafaSafari** [comment]
nice bro
thank you :kissing: 
I will fix that on the next commit :))
I'm closing this issue, if you have any questions, reopen that :))
